server:
  port: 1002
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sharding-jdbc-002
  # Sharding-JDBC的配置
  shardingsphere:
    datasource:
      # 数据源，这里配置两个，分别是ds1，ds2
      names: ds1,ds2
      # ds1的配置信息,product_db1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/product_db1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: Nov2014
      # ds2的配置信息,product_db2
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/product_db2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: Nov2014
    # 分片的配置
    sharding:
      # 表的分片策略
      tables:
        product_base:
          # 数据节点配置，采用Groovy表达式，分库分表策略，这样是4个节点，ds1.product_base_$_1/ds1.product_base_$_2/ds2.product_base_$_1/ds2.product_base_$_2
          actual-data-nodes: ds$->{1..2}.product_base_$->{1..2}
          # 分表策略
          table‐strategy:
            standard:
              sharding‐column: product_id
              precise-algorithm-class-name: com.java.family.shardingjdbc004.algorithm.TablesPreciseShardingAlgorithm
          # 分库策略
          database‐strategy:
            # 标准分片策略
            standard:
              # 分片键
              sharding‐column: shop_id
              # 精确分片算法
              precise-algorithm-class-name: com.java.family.shardingjdbc004.algorithm.DataSourcePreciseShardingAlgorithm
              # 范围分片算法
              range-algorithm-class-name: com.java.family.shardingjdbc004.algorithm.DataSourceRangeShardingAlgorithm
          # 主键生成策略
          key-generator:
            # 主键
            column: product_id
            # 生成算法
            type: SNOWFLAKE
        product_description:
          # 数据节点配置，采用Groovy表达式
          actual-data-nodes: ds$->{1..2}.product_description_$->{1..2}
          table‐strategy:
            standard:
              sharding‐column: product_id
              precise-algorithm-class-name: com.java.family.shardingjdbc004.algorithm.TablesPreciseShardingAlgorithm
          # 分库策略
          database‐strategy:
            standard:
              sharding‐column: shop_id
              precise-algorithm-class-name: com.java.family.shardingjdbc004.algorithm.DataSourcePreciseShardingAlgorithm
              range-algorithm-class-name: com.java.family.shardingjdbc004.algorithm.DataSourceRangeShardingAlgorithm
        shop:
          # 数据节点配置，采用Groovy表达式
          actual-data-nodes: ds$->{1}.shop
          # 主键生成策略
          key-generator:
            # 主键
            column: shop_id
            # 生成算法
            type: SNOWFLAKE
      ## 绑定表的规则配置，可以配置多个，集合形式
      binding-tables:
        - product_base,product_description
      ## 指定广播表，集合形式
      broadcast‐tables:
        - product_type
    props:
      sql:
        # 日志显示具体的SQL
        show: true
